/* Portafolio de Claudio Martínez Meza — generado desde Drive */
window.PORTAFOLIO = [
{
"slug": "testimonio-padresito",
"title": "Testimonio Iglesia",
"brand": "I-Vert Energy",
"cat": "testimonios",
"catName": "Testimonios",
"id": "1Qfw0fITYTh-LdKzvooXyqMhRf9XbrvYK",
"vertical": false,
"dur": "3:09",
"poster": "assets/portafolio/testimonio-padresito.jpg",
"featured": true
},
{
"slug": "testimonio-peter-boller",
"title": "Testimonio Peter Boller",
"brand": "I-Vert Energy",
"cat": "testimonios",
"catName": "Testimonios",
"id": "1-IcEJpH_fpoOcGBqbAxf5nikrl1OZKKD",
"vertical": false,
"dur": "0:47",
"poster": "assets/portafolio/testimonio-peter-boller.jpg",
"featured": true
},
{
"slug": "video-institucional-4-aniversario",
"title": "Video institucional 4º aniversario",
"brand": "Valori+",
"cat": "institucional",
"catName": "Institucional",
"id": "1po24FtKSWH2Tk7r5GrT_Bf-0QCVHgzjz",
"vertical": false,
"dur": "15:15",
"poster": "assets/portafolio/video-institucional-4-aniversario.jpg",
"featured": true
},
{
"slug": "work-shop-video",
"title": "Workshop Valori+",
"brand": "Valori+",
"cat": "institucional",
"catName": "Institucional",
"id": "1o3L3uZXvstgnX6oaHnc8T7ZSvOi3DBR3",
"vertical": false,
"dur": "0:57",
"poster": "assets/portafolio/work-shop-video.jpg",
"featured": true
},
{
"slug": "testimonio-carol-wells",
"title": "Testimonio Carol Wells",
"brand": "I-Vert Energy",
"cat": "testimonios",
"catName": "Testimonios",
"id": "16zoaiviz4CPRqofoyjzpw-aMmt2WshUB",
"vertical": false,
"dur": "1:06",
"poster": "assets/portafolio/testimonio-carol-wells.jpg",
"featured": false
},
{
"slug": "testimonio-carol-wells-reel",
"title": "Testimonio Carol Wells (reel)",
"brand": "I-Vert Energy",
"cat": "testimonios",
"catName": "Testimonios",
"id": "1dS0pYdiIGb07tmxd0qkyOe5lcu5YQg_Q",
"vertical": true,
"dur": "0:39",
"poster": "assets/portafolio/testimonio-carol-wells-reel.jpg",
"featured": false
},
{
"slug": "testimonio-tony",
"title": "Testimonio Tony",
"brand": "I-Vert Energy",
"cat": "testimonios",
"catName": "Testimonios",
"id": "12DH5sewQSkmAWLDm905Rz58-t9SEsi3_",
"vertical": false,
"dur": "1:07",
"poster": "assets/portafolio/testimonio-tony.jpg",
"featured": false
},
{
"slug": "adrian-acunaga-testimonio-youtube",
"title": "Testimonio Adrián Acuñaga",
"brand": "Valori+",
"cat": "testimonios",
"catName": "Testimonios",
"id": "1NiqIGS0-QHP4C0RI_oTSiIEST0pRb-aA",
"vertical": false,
"dur": "3:38",
"poster": "assets/portafolio/adrian-acunaga-testimonio-youtube.jpg",
"featured": false
},
{
"slug": "reel-aniversario",
"title": "Reel aniversario",
"brand": "Valori+",
"cat": "institucional",
"catName": "Institucional",
"id": "1CATT2F720K4a66E7kF2KgzrLBV10kh9A",
"vertical": true,
"dur": "0:42",
"poster": "assets/portafolio/reel-aniversario.jpg",
"featured": false
},
{
"slug": "reel-leydy-castillo",
"title": "Reel Leydy Castillo",
"brand": "",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1ioDyGdW-yZA4RWnhA7o7Nn64bkw3dC4G",
"vertical": true,
"dur": "1:06",
"poster": "assets/portafolio/reel-leydy-castillo.jpg",
"featured": false
},
{
"slug": "reel-vestidos",
"title": "Reel Vestidos",
"brand": "",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1XYjpPWrcFvKlxDhMe6EMNKEviAWS3Qu4",
"vertical": true,
"dur": "0:59",
"poster": "assets/portafolio/reel-vestidos.jpg",
"featured": false
},
{
"slug": "curso-interconectados-ciit-solar",
"title": "Curso Sistemas Interconectados",
"brand": "CITSolar",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1uEk50ZypjwvPL7E3PG9HLJHo5upaSTHy",
"vertical": true,
"dur": "0:54",
"poster": "assets/portafolio/curso-interconectados-ciit-solar.jpg",
"featured": false
},
{
"slug": "recap-curso-citsolar",
"title": "Recap curso CITSolar",
"brand": "CITSolar",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1vkehX9F79ktz1d_n5SmYU5g-I43anJwx",
"vertical": true,
"dur": "1:00",
"poster": "assets/portafolio/recap-curso-citsolar.jpg",
"featured": false
},
{
"slug": "reel-2-citsolar",
"title": "Reel CITSolar",
"brand": "CITSolar",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "15Ciq_PJz436xNf11Fywl8sdzvaHtisLl",
"vertical": true,
"dur": "1:04",
"poster": "assets/portafolio/reel-2-citsolar.jpg",
"featured": false
},
{
"slug": "reel-citsolar-2",
"title": "Reel CITSolar II",
"brand": "CITSolar",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "16jTW9e1VRhVjytYifCBIwFEDCtlwjFzP",
"vertical": true,
"dur": "0:57",
"poster": "assets/portafolio/reel-citsolar-2.jpg",
"featured": false
},
{
"slug": "sistema-solar-por-un-experto-reel",
"title": "Sistema solar por un experto",
"brand": "CITSolar",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1NPwjRkHSFIiGVeCfzVYOfX-b3fowRcwL",
"vertical": true,
"dur": "1:26",
"poster": "assets/portafolio/sistema-solar-por-un-experto-reel.jpg",
"featured": false
},
{
"slug": "webinar-09-junio",
"title": "Webinar 9 de junio",
"brand": "CITSolar",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "13Nl4tw4N0SQO8WRmYzajLkogJY9BbG9N",
"vertical": true,
"dur": "0:54",
"poster": "assets/portafolio/webinar-09-junio.jpg",
"featured": false
},
{
"slug": "fisioterapia-a-domicilio",
"title": "Fisioterapia a Domicilio",
"brand": "Fisioterapia a Domicilio",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "18T0_SHkRZPz1x_ZvuKqFfrGFMwbCfoOl",
"vertical": true,
"dur": "0:57",
"poster": "assets/portafolio/fisioterapia-a-domicilio.jpg",
"featured": false
},
{
"slug": "chrismast-with-i-vert-energy-reel",
"title": "Christmas with I-Vert Energy",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1VpemA6ZP43d8nxc311OjdwMBAHWoqjc6",
"vertical": true,
"dur": "1:39",
"poster": "assets/portafolio/chrismast-with-i-vert-energy-reel.jpg",
"featured": false
},
{
"slug": "do-solar-panels-wokrs-in-heat",
"title": "Do solar panels work in heat?",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1MwpaWnxQsg_OpjbajOMaYLZmYTcqImtf",
"vertical": true,
"dur": "0:30",
"poster": "assets/portafolio/do-solar-panels-wokrs-in-heat.jpg",
"featured": false
},
{
"slug": "evento-bingo",
"title": "Evento Bingo",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1DcyCtkAM2ygbKrSkZQVS_9rgIlCjgoIX",
"vertical": true,
"dur": "0:57",
"poster": "assets/portafolio/evento-bingo.jpg",
"featured": false
},
{
"slug": "reel-no-cotizaron-2",
"title": "No cotizaron",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1iyUpu77RvYKDmAv5bj3Xlcv5AgeEBHsu",
"vertical": true,
"dur": "0:18",
"poster": "assets/portafolio/reel-no-cotizaron-2.jpg",
"featured": false
},
{
"slug": "paquetes-i-vert-energy",
"title": "Paquetes I-Vert",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1KKWC4pedHPzK-3BER_gJknDY9GbRNAA1",
"vertical": true,
"dur": "0:37",
"poster": "assets/portafolio/paquetes-i-vert-energy.jpg",
"featured": false
},
{
"slug": "paquetes-2-i-vert-energy",
"title": "Paquetes I-Vert II",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1E0f5joHqybmJfBofLngH1bhTAdTXnBBt",
"vertical": true,
"dur": "0:18",
"poster": "assets/portafolio/paquetes-2-i-vert-energy.jpg",
"featured": false
},
{
"slug": "paquetes-3-ivert-energy",
"title": "Paquetes I-Vert III",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1sOxCzPnObkaL-ngd7WqpiIfVo6_gtOVI",
"vertical": true,
"dur": "0:30",
"poster": "assets/portafolio/paquetes-3-ivert-energy.jpg",
"featured": false
},
{
"slug": "paquetes-san-felipe",
"title": "Paquetes San Felipe",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1BpJQngw2oZFuTe3EJyUIDHbTQNw8O6ay",
"vertical": true,
"dur": "0:39",
"poster": "assets/portafolio/paquetes-san-felipe.jpg",
"featured": false
},
{
"slug": "paquetes-diciembre-3-reel",
"title": "Paquetes de diciembre",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1N7tVBpeYoE2bKvJ_6bXi6_BG8UDm2xQO",
"vertical": true,
"dur": "0:30",
"poster": "assets/portafolio/paquetes-diciembre-3-reel.jpg",
"featured": false
},
{
"slug": "reel-premios",
"title": "Premios",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1bEz52OkxDL3IYqtLg9bWuzmZk_2hFYKT",
"vertical": true,
"dur": "1:18",
"poster": "assets/portafolio/reel-premios.jpg",
"featured": false
},
{
"slug": "reel-2-analizan",
"title": "Reel Analizan",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1mOTrOiyojgjAwkrrZDFgAenFTMlZ12Ta",
"vertical": true,
"dur": "0:54",
"poster": "assets/portafolio/reel-2-analizan.jpg",
"featured": false
},
{
"slug": "cuantos-paneles-necesitas-reel",
"title": "¿Cuántos paneles necesitas?",
"brand": "I-Vert Energy",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "10aHcIssi1ASsudY0qaz_bmANLuJaUr7K",
"vertical": true,
"dur": "0:31",
"poster": "assets/portafolio/cuantos-paneles-necesitas-reel.jpg",
"featured": false
},
{
"slug": "aniversario-valori",
"title": "Aniversario Valori+",
"brand": "Valori+",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1-rr8bEnmGqSaSY-b7ofIU0qe-ZQAjXqV",
"vertical": true,
"dur": "0:35",
"poster": "assets/portafolio/aniversario-valori.jpg",
"featured": false
},
{
"slug": "reel-tarjetas",
"title": "Reel Tarjetas",
"brand": "Valori+",
"cat": "campanas",
"catName": "Campañas publicitarias",
"id": "1zpA-FgaXDItDccQrAO4xkSsGEz947bfq",
"vertical": true,
"dur": "1:46",
"poster": "assets/portafolio/reel-tarjetas.jpg",
"featured": false
},
{
"slug": "invitacion-ingles",
"title": "Invitación (EN)",
"brand": "",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "149QPoIXoCm2Gw0caz6onIilhIAr67998",
"vertical": true,
"dur": "0:18",
"poster": "assets/portafolio/invitacion-ingles.jpg",
"featured": false
},
{
"slug": "do-you-want-more-power-reel",
"title": "Do you want more power?",
"brand": "I-Vert Energy",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "1KCys2a-a24-KmVrx-kKaG-W3B08Em-jh",
"vertical": true,
"dur": "0:17",
"poster": "assets/portafolio/do-you-want-more-power-reel.jpg",
"featured": false
},
{
"slug": "paquetes-septiembre-reel",
"title": "Paquetes de septiembre",
"brand": "I-Vert Energy",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "17KlPm7kPrp4FOqmgB9weWEcwGQIQYGAp",
"vertical": true,
"dur": "0:28",
"poster": "assets/portafolio/paquetes-septiembre-reel.jpg",
"featured": false
},
{
"slug": "reel-sistemas-interconectados",
"title": "Sistemas interconectados",
"brand": "I-Vert Energy",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "1PyG2KsuckDBhrKSyGzgvnt6A3vHCf6Ux",
"vertical": true,
"dur": "0:39",
"poster": "assets/portafolio/reel-sistemas-interconectados.jpg",
"featured": false
},
{
"slug": "this-is-the-best-reel",
"title": "This is the best",
"brand": "I-Vert Energy",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "1aNdV-TtYbrfPjpGNZ5b4DZjj3hvMz_n-",
"vertical": true,
"dur": "0:20",
"poster": "assets/portafolio/this-is-the-best-reel.jpg",
"featured": false
},
{
"slug": "somos-de-san-felipe-ingles-reel",
"title": "We are from San Felipe",
"brand": "I-Vert Energy",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "1-GmY5mrr6G1hlangfa_4IGSo8e6hIQAE",
"vertical": true,
"dur": "0:25",
"poster": "assets/portafolio/somos-de-san-felipe-ingles-reel.jpg",
"featured": false
},
{
"slug": "we-are-in-all-san-felipe-reel",
"title": "We are in all San Felipe",
"brand": "I-Vert Energy",
"cat": "contenido",
"catName": "Contenido para redes",
"id": "1c7ep-IDBZmWkJrU_q9i7wb7sj5ncSRwy",
"vertical": true,
"dur": "0:27",
"poster": "assets/portafolio/we-are-in-all-san-felipe-reel.jpg",
"featured": false
},
{
"slug": "intro-cotton",
"title": "Intro Cotton Calexico",
"brand": "Cotton Calexico",
"cat": "animacion",
"catName": "Animación",
"id": "1gombWysQwd-QiCmi9gTkWncqPnDjSgEn",
"vertical": true,
"dur": "0:05",
"poster": "assets/portafolio/intro-cotton.jpg",
"featured": false
},
{
"slug": "intro-el-dinero-en-mi-historia-final",
"title": "Intro: El dinero en mi historia",
"brand": "Valori+",
"cat": "animacion",
"catName": "Animación",
"id": "1Wjl0zxJMGwO12Ty3CIj-8TsF2VCYyW8N",
"vertical": false,
"dur": "0:14",
"poster": "assets/portafolio/intro-el-dinero-en-mi-historia-final.jpg",
"featured": false
},
{
"slug": "atropellado-son",
"title": "Atropellado",
"brand": "Canal 66",
"cat": "notas",
"catName": "Notas periodísticas",
"id": "1yj_tBoTpMQOXqaGIaaRKwREqd1e5MzXS",
"vertical": false,
"dur": "1:14",
"poster": "assets/portafolio/atropellado-son.jpg",
"featured": false
},
{
"slug": "comite-confusion-son",
"title": "Comité: confusión",
"brand": "Canal 66",
"cat": "notas",
"catName": "Notas periodísticas",
"id": "1Y1fqn5F8_mNKyVobQ4h8cRO0q2Z3lvaZ",
"vertical": false,
"dur": "2:39",
"poster": "assets/portafolio/comite-confusion-son.jpg",
"featured": false
},
{
"slug": "eleccion-pj-son",
"title": "Elección del Poder Judicial",
"brand": "Canal 66",
"cat": "notas",
"catName": "Notas periodísticas",
"id": "1KkUDkBdLhOmYLaSsMmBtNBVBoAJvZ2J4",
"vertical": false,
"dur": "2:12",
"poster": "assets/portafolio/eleccion-pj-son.jpg",
"featured": false
},
{
"slug": "ley-dariela-son",
"title": "Ley Dariela",
"brand": "Canal 66",
"cat": "notas",
"catName": "Notas periodísticas",
"id": "1ZOZY54fgUbitOL57fkQS4gH6VpSyc2xh",
"vertical": false,
"dur": "2:05",
"poster": "assets/portafolio/ley-dariela-son.jpg",
"featured": false
},
{
"slug": "ley-ingresos-son",
"title": "Ley de Ingresos",
"brand": "Canal 66",
"cat": "notas",
"catName": "Notas periodísticas",
"id": "1RPMdY3XvTkTBb21bfvwyEsSFWVi7LSDz",
"vertical": false,
"dur": "1:53",
"poster": "assets/portafolio/ley-ingresos-son.jpg",
"featured": false
},
{
"slug": "manifestacion-agua-son",
"title": "Manifestación por el agua",
"brand": "Canal 66",
"cat": "notas",
"catName": "Notas periodísticas",
"id": "1q9boflyYWbaYcydeiHadtd1vIgUB1QAh",
"vertical": false,
"dur": "2:49",
"poster": "assets/portafolio/manifestacion-agua-son.jpg",
"featured": false
}
];
